version: '3'
services:
  php:
    build: .
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - redis
    environment:
      # The "redis" value for REDIS_HOST matches the name of the container defined below
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:6-alpine

  webserver:
    image: nginx:1.16-alpine
    depends_on:
      - php
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
